//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.UserPages {
    
    
    public partial class TeacherHome {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WebApplication.UserPages.Teacher Master {
            get {
                return ((WebApplication.UserPages.Teacher)(base.Master));
            }
        }
    }
}
